Before we get start, two facts about the determinant:

1. $\det(AB) = \det(A)\det(B)$

2. The determinant of a diagonal matrix is the product of the diagonal

Given a two-qubit unitary matrix $U \in U(4)$, we can decompose them into 

$$U = e^{i\phi}K_1 A K_2$$

where $e^{i\phi}$ is a global phase

$K_1, K_2$ are local gates ($K_1 = A_1 \otimes B_1$ and $K_2 = A_2 \otimes B_2$ for single qubit $A_1, A_2, B_1, B_2$).

and $A = e^{\frac{i}{2}(k_X \sigma_X^2 + k_Y\sigma_Y^2 + k_Z \sigma_Z^2)}$ for canonical parameters $k_X, k_Y, k_Z \in [0, \pi]$

### 1. Global Phase

First, we want normalize the determinant of the matrix to make sure $U \in SU(4)$. 

- Since $\det(\alpha A) =\alpha^{\dim(A)}\det(A)$, we set $\alpha = \det(A)^{-\frac{1}{\dim(A)}}$ to ensure $\det(\alpha A) = 1$. 

In other words, $e^{i\phi} = \det(A)^{-\frac{1}{\dim(A)}}$

### 2. KAK Decomposition

We use an important theorem from Lie algebra called the Cartan decomposition, which states the following:

Fact 1. Given $U \in SU(4)$, $U = KM$ for $K \in SO(4)$ and $M = e^{i(a_1 IZ + a_2 ZI + a_3 ZZ + ...)}$ (more Pauli tensor product terms)

Fact 2. The term $M$ can be further decomposed (by conjugation) $M = K_2^\dagger A K_2$ where $K_2 \in SO(4)$ and $A = e^{i(a_1 IZ + a_2 ZI + a_3 ZZ)}$

Combine these two facts, we get the decomposition 

$$U = KK_2^\dagger A K_2 = K_1 A K_2$$

To find these blocks, we make use of the Cartan function (involution) $\Theta$. This function detects whether a unitary matrix falls into the $K$-type or the $M$-type.

$$\Theta(U) = \begin{cases}U \quad &\text{ if } U \text{ is $K$-type} \\ U^\dagger \quad &\text{ if } U \text{ is $M$-type}\end{cases}$$

For two-qubit unitary matrices, $\Theta(U) = U^\ast$. We can isolate $M$ with the product $\Theta(U^\dagger)U$:

\begin{align}\Theta(U^\dagger)U &= \Theta(M^\dagger K^\dagger)KM \\ &= \Theta (M^\dagger) \Theta(K^\dagger) KM \\ &= (MK^\dagger)K M \\ &= M^2\end{align}

In our case, $\Theta(U^\dagger)U  = U^TU$ (**explain**)

In Fact 2, observe that $A$ is a diagonal matrix (**explain**). So we can easily find $A$ from $M$ by diagonalization. 

$$M^2 = P D P^\dagger$$

It is obvious that $K_2 = P^\dagger$ and $A = \sqrt D$ (**explain** what the square root mean). Since $U = K_1 A K_2$, $K_1 = U K_2^\dagger A^\dagger$. There you go, KAK decomposition

### 3. Canonical Parameters

Again from Fact 2, $A = e^{i(a_1 IZ + a_2 ZI + a_3 ZZ)}$. Expanding this fully, we get

\begin{align}A = 
\begin{pmatrix} 
e^{i(a_0+a_1+a_2)} & 0 & 0 & 0 \\
0 & e^{i(-a_0+a_1-a_2)} & 0 & 0 \\
0 & 0 & e^{i(a_0-a_1-a_2)} & 0 \\
0 & 0 & 0 & e^{i(-a_0-a_1+a_2)} \\
\end{pmatrix} &=
\begin{pmatrix} 
e^{i\theta_0} & 0 & 0 & 0 \\
0 & e^{i\theta_1} & 0 & 0 \\
0 & 0 & e^{i\theta_2} & 0 \\
0 & 0 & 0 & e^{-i(\theta_0 + \theta_1 + \theta_2)} \\
\end{pmatrix}
\end{align}

The final matrix is obtained by diagonalization $A = \sqrt D$ from before. 
explain the structure of this matrix.

Equating the phase to each other

\begin{align}
a_0+a_1+a_2 &= \theta_0 \\
-a_0+a_1-a_2 &= \theta_1 \\
a_0-a_1-a_2 &= \theta_2 \\
-a_0-a_1+a_2 &= -(\theta_0 + \theta_1 + \theta_2)
\end{align}

Notice that the last equation is just the negative of the sum of the first three equations, therefore it is redundant. Hence, we have three equations on three variables. This means that we can set up a matrix equation and solve by taking the inverse.

$$\underbrace{\begin{pmatrix} 
1 & 1 & 1 \\
-1 & 1 & -1 \\
1 & -1 & -1
\end{pmatrix}}_{C} 
\underbrace{\begin{pmatrix}
a_0 \\ a_1 \\ a_2
\end{pmatrix}}_{\vec{a}} = 
\underbrace{\begin{pmatrix}
\theta_0 \\ \theta_1 \\ \theta_2
\end{pmatrix}}_{\vec{c}}$$

Then the desired parameters are simply $\vec{a} = C^{-1} \vec{\theta}$. In fact, we give the explicit expression for $C^{-1}$:

$$C^{-1} = \frac{1}{2} \begin{pmatrix} 1 & 0 & 1 \\ 1 & 1 & 0 \\ 0 & -1 & -1 \end{pmatrix}$$

This gives us the canonical parameters

### 4. Magic Basis

So far, we obtain the KAK decomposition 

$$U = K_1 A K_2$$

where $K_1, K_2 \in SO(4)$ and $A = e^{\frac{i}{2}(a_1 IZ + a_2 ZI + a_3 ZZ)}$.

However, we want

$K_1, K_2 \in SU(2) \otimes SU(2)$ and $A = e^{\frac{i}{2}(c_1 XX + c_2 YY + c_3 ZZ)}$

Fortunately, we can make use of what's called a "magic-basis" that allows us to easily translate between these two.

$$B = \frac{1}{\sqrt2}
\begin{pmatrix} 
1 & 0 & 0 & i \\
0 & i & 1 & 0 \\
0 & i & -1 & 0 \\
1 & 0 & 0 & -i
\end{pmatrix}$$

Fact 3. $B^\dagger SO(4) B \to SU(2)\otimes SU(2)$. That is if we conjugate a $SO(4)$ matrix, we get another matrix that is separable into tensor product of $SU(2)$.

Fact 4. $B^\dagger e^{i(a_1 IZ + a_2 ZI + a_3 ZZ)}B = e^{\frac{i}{2}(c_1 XX + c_2 YY + c_3 ZZ)}$, where $c_{0} = 2a_1, c_{1} = -2a_0, c_{2} = 2a_2$.

Combine these two facts, we get

\begin{align} U
&= B^\dagger \cdot SO(4) \cdot e^{i(a_1 IZ + a_2 ZI + a_3 ZZ)} \cdot SO(4) \cdot B \\
&= \big(B^\dagger SO(4) B \big) \big(B^\dagger e^{i(a_1 IZ + a_2 ZI + a_3 ZZ)} B \big) \big(B^\dagger SO(4) B\big) \\
&= \big(SU(2) \otimes SU(2) \big)e^{\frac{i}{2}(c_1 XX + c_2 YY + c_3 ZZ)}\big(SU(2) \otimes SU(2) \big)
\end{align}

Talk about adjoint orbit theorem, how the local gates has 6 parameters, 

Explain the formation of the chamber as equivalence class from period

Explain the purpose of symmetry reduction as unique representation, equivalence class

As gate how there is local gates corresponding to them (tucci) and combinations of these gates from the Weyl group.

Then how there is 6 planes from symmetry. Go through the motion of division and choosing euqivalence class. 

Last time, we derive a scheme for decomposing a two-qubit unitary into local gates and a canonical gate.

\begin{align} U = \big(SU(2) \otimes SU(2) \big)e^{\frac{i}{2}(c_1 XX + c_2 YY + c_3 ZZ)}\big(SU(2) \otimes SU(2) \big)
\end{align}

From now, I will refer to this as the canonical gate

$$CAN(c_1, c_2, c_3) = e^{\frac{i}{2}(c_1 XX + c_2 YY + c_3 ZZ)}$$

We also come up with a method to determnine the canonical parameters $c_1, c_2, c_3$ using linear algebra. Motivated by experimental difficulty in implementing non-local gates, we investigate further the structure of the canonical gates.

However, there is an inherent flaw with our result so far, because these parameters $c_1, c_2, c_3$ is not unique. To make this clearer, we'll introduce the concept of local equivalence:

Two gates are **locally equivalent**, if one can be transform into another by pre (and post) composition of local gates. 

So our problem is that there are multiple sets of parameters which construct the locally equivalent gates!

For example, if you add $\pi$ in the $c_1$, you will observe that

$$\exp{\frac{i}{2}\big[(c_1+\pi) \sigma_x^{1, 2} + c_2 \sigma_y^{1, 2} + c_3 \sigma_z^{1, 2}\big]} = i\sigma_x^{1, 2} \cdot \exp{\frac{i}{2}\big[c_1 \sigma_x^{1, 2} + c_2 \sigma_y^{1, 2} + c_3 \sigma_z^{1, 2}\big]}$$

Our goal is to come up with a scheme to characterize all these locally equivalent two-qubit gates, and essentially resprent them uniquely.

Before, doing that, I want to introduce an anlogous problem from modular arithmetic.

- Introduce mod, and equivalence class - quotient set, also representation of set [a].

We shall proceed in a similar fashion. 

Recall the Fact 2. from last time, which states that:

The term $M$ can be further decomposed (by conjugation) $M = K_2^\dagger A K_2$ where $K_2 \in SO(4)$ and $A = e^{i(a_1 IZ + a_2 ZI + a_3 ZZ)}$. 

Also, recall Fact 3. from last time, which states that: $B^\dagger SO(4) B \to SU(2)\otimes SU(2)$

Combining these two facts, we can deduce that $SO(4)$ has 6 degrees of freedom (3 from each $SU(2)$). Just keep this number in mind for a moment.

First, we need to identify the space of our canonical parameters. Ok, so $c_1, c_2, c_3$, what are they? They are angles, so they are just real number. So right now, they live in $\mathbb{R}^3$. But notice, that if we add $\pi$ to any parameter and compute the matrix exponential, we get a locally equivalent gate. This reveals a "periodicity" of the canonical gate. To gate some more familiarity on this, let's look at the cosine function...

This periodicity tells us that if we look at the region $[0, 1] \times [0, 1] \times [0, 1]$, we get all the information about the whole space, so let's focus our attention to that. Very simply, this is a cube at the positive x, y, z quadrant with side length 1.

Now, we can start our "symmetry-reduction" of this cube into the tetrahedron!

As the name suggest, we should look at symmetry of the canonical gate. One of the thing, we can try is to swap the position of any two parameters, for example

$$[c_1, c_2, c_3] \to [c_2, c_1, c_3]$$

Computing the matrix exponential, we find that

$$\exp{\frac{i}{2}\big[\mathbf{c_2} \sigma_x^{1, 2} + \mathbf{c_1} \sigma_y^{1, 2} + c_3 \sigma_z^{1, 2}\big]} = \exp -\frac{i\pi}{4} \big(\sigma_z^1 + \sigma_z^2 \big) \cdot  \exp{\frac{i}{2}\big[c_1 \sigma_x^{1, 2} + c_2 \sigma_y^{1, 2} + c_3 \sigma_z^{1, 2}\big]} \cdot \exp \frac{i\pi}{4} \big(\sigma_z^1 + \sigma_z^2 \big)$$

Another thing, we can do is to flip two parameters and negate them. For example,

$$[c_1, c_2, c_3] \to [-c_2, -c_1, c_3]$$

It's your turn to show that this is locally equivalent to the original gate.

Let's see these transformation geometrically

In [36]:
a0, b0, c0, d0 = np.triu(np.random.rand(4, 4, 4))

In [34]:
b = lambda x, y: x@y-y@x

In [43]:
a1 = b(a0, b0)

In [44]:
b1 = b(c0, d0)

In [46]:
a2 = b(a1, b1)

In [47]:
b(a1, a2)

array([[0.        , 0.        , 0.        , 0.00151333],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [48]:
a1

array([[ 0.        , -0.0011966 , -0.5156578 , -0.42806602],
       [ 0.        ,  0.        , -0.10980098, -0.23509923],
       [ 0.        ,  0.        ,  0.        ,  0.08114093],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [49]:
a2

array([[ 0.        ,  0.        , -0.01929257,  0.18692308],
       [ 0.        ,  0.        ,  0.        ,  0.04353146],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])