This notebook summarizes and implements results from [A geometric theory of non-local two-qubit operations](https://arxiv.org/pdf/quant-ph/0209120.pdf) by Zhang et al. .

### 1. Background

**Definition (Conjugation Map):** The **conjugation map** from the Lie group $G$ to $G$ given by $a_g(h) = ghg^{-1}$, where $g, h \in G$.

**Definition (Adjoint Representation):** The **adjoint representation** $\text{Ad}_g$ is a map from the Lie algebra $\mathfrak{g}$ to $\mathfrak{g}$ which is the differential of the conjugation map $a_g$. For matrix Lie algebras, $\text{Ad}_g(Y)=gYg^{-1}$ where $g \in G$ and $Y \in \mathfrak{g}$.

**Definition (Lie Bracket):** The differential of the adjoint representation $\text{ad}_X$ is a map from the lie algebra $\mathfrak{g}$ to $\mathfrak{g}$ given by the Lie bracket with $X$, that is, $\text{ad}_X(Y)=[X, Y]$, where $X, Y \in \mathfrak{g}$.

**Definition (Killing Form):** The inner product on $\mathfrak{g}$ is given by the **Killing form** $B(X, Y) = \text{tr}(\text{ad}_X\text{ad}_Y)$. Since $\text{ad}_X$ and $\text{ad}_Y$ are both linear maps, the Killing form is the trace of their composition.

**Definition (Structure Constants):** Let $\{X_1, ..., X_n\}$ be a basis for $\mathfrak{g}$. The numbers $C_{jk}^{i} \in \mathbb{C}$ such that

$$[X_j, X_k] = \sum_{i=1}^n C_{jk}^{i}X_i$$

are the **structure constants** of the Lie algebra $\mathfrak{g}$ with respect to the basis, where $j, k$ run from $1$ to $n$. Consider the vectorized expression

\begin{align}\text{ad}_{X_j}[X_1, ..., X_n] 
&= [\sum_{i=1}^n C_{j1}^{i}X_i, ..., \sum_{i=1}^n C_{jn}^{i}X_i] \\
&= [X_1, ..., X_n]\begin{bmatrix}C_{j1}^1 & \ldots & C_{jn}^1 \\ \vdots & & \vdots \\ C_{j1}^n & \ldots & C_{jn}^n \end{bmatrix}\end{align}

Hence, the matrix represenation of $\text{ad}_{X_j}$ with respect to the basis is 

\begin{bmatrix}C_{j1}^1 & \ldots & C_{jn}^1 \\ \vdots & & \vdots \\ C_{j1}^n & \ldots & C_{jn}^n \end{bmatrix}

Thus the Killing form $B(X_j, X_k)$ is $\sum_{a, b = 1}^n C_{jb}^a C_{ka}^b$, which is the $jk$-th enetry of the matrix of the quadratic form $B(, )$ or $x^T(\text{ad}_X\text{ad}_Y)x$. 

**Definition (Semisimple):** The Lie algebra $\mathfrak{g}$ is **semisimple** if and only if the Killing form is nondegenerate

**Defintion (Root):** Given a semisimple Lie algebra $\mathfrak{g}$ and its Cartan decomposition $\mathfrak{g} = \mathfrak{p} \oplus \mathfrak{l}$, let $\mathfrak{a}$ be a Cartan sublagebra of the pair $(\mathfrak{g}, \mathfrak{l})$. For $X \in \mathfrak{a}$, let $W \in \mathfrak{g}$ be an eigenvector of $\text{ad}_X$ and $\alpha(X)$ the corresponding eigenvalue, i.e., 

$$[X, W] = \langle \alpha, X\rangle \cdot W$$

The linear map $\alpha$ is called a **root** of $\mathfrak{g}$ with respect to $\mathfrak{a}$. In other words, they are the eigenvalues of the matrix $\text{ad}_X$. 

Let $\Delta$ denote the set of nonzero roots, and $\Delta_{\mathfrak{p}} \subseteq \Delta$ denote the set of roots in which do not vanish identically on $\mathfrak{a}$:

\begin{align} \Delta &= \{\alpha \ : \ [X, W] = \langle \alpha, X\rangle \cdot W, \text{where } W \in \mathfrak{g}\} \\
\Delta_{\mathfrak{p}} &= \{\alpha \ : \ [X, W] = \langle \alpha, X\rangle \cdot W, \text{where } W \in \mathfrak{a}\}
\end{align}

**Definition (Centralizer):** The **centralizer** of $\mathfrak{a}$ in $K$ is the set 

$$M = \{k \in K : \text{Ad}_k(X) = X \text{ for each } X \in \mathfrak{a}\}$$

Since $kXk^{-1} = X$, this implies that $kX = Xk$. In other words, the **centralizer** is the set of elements in $K$ that commutes with everything in $\mathfrak{a}$.

**Definition (Normalizer):** The **normalizer** of $\mathfrak{a}$ in $K$ is the set 

$$M^{\prime} = \{k \in K : \text{Ad}_k(\mathfrak{a}) \subseteq \mathfrak{a}\}$$

In other words, the **normalizer** is the set of elements in $K$ whose $\mathfrak{a}$-adjoint action is closed in $\mathfrak{a}$.

**Definition (Weyl group):** The **Weyl group** $W(G, K)$ is the quotient group $M^\prime / M$. One can show that $W(G, K)$ is a finite group. This comes from the fact that $\mathfrak{g}$ is a finite dimensional vector space.

**Definition (Weyl chamber):** Each $\alpha \in \Delta_{\mathfrak{p}}$ defines a hyperplane $\langle\alpha, X\rangle = 0$ in the vector space $\mathfrak{a}$. These hyper planes divide the space $\mathfrak{a}$ into finitely many connected components, called the **Weyl chambers**.

**Proposition (Generation of the Weyl group)**: For each $\alpha \in \Delta_{\mathfrak{p}}$, let $s_\alpha$ denote the reflection with respect to the hyperplane $\langle \alpha, X\rangle = 0$ in $\mathfrak{a}$. The Weyl group is **generated** by the reflections $s_\alpha, \alpha \in \Delta_{\mathfrak{p}}$.

### 2. Applications to $\mathfrak{su}(2)$

From computing the structure constants $C^i_{jk}$, we can evaluate the Killing form

$$B(X_j, X_k) = \sum_{a=1}^{2^n-1} \sum_{b=1}^{2^n-1} C^a_{jb}C^b_{ka} = -2n \cdot \delta_{jk}$$

It is easy to verify that $\text{tr}(X_j X_k) = -\delta_{jk}$, thus the Killing form of $\mathfrak{su}(n)$ is $B(X, Y) = 2n\cdot \text{tr}(XY)$.

In [156]:
import numpy as np
from sympy import Matrix, symbols, I, eye, expand, simplify
from itertools import product

In [157]:
X0 = np.array([[1, 0], [0, 1]])
X1 = np.array([[0, 1], [1, 0]])
X2 = np.array([[0, 1j], [-1j, 0]])
X3 = np.array([[1, 0], [0, -1]])

pauli = [X0, X1, X2, X3]

Lie_bracket = lambda x, y: x@y-y@x

In [214]:
def generate_pauli_bases(num_qubits):
    if num_qubits == 1:
        return [1j/2*basis for basis in pauli[1:]]
    else: # Divide by two to help normalize the Lie bracket
        return [
            1j / 2 * np.kron(*basis)
            for basis in product(pauli, repeat=num_qubits)
        ][1:]

In [217]:
def structure_constant(X, method = "partial"):
    """Generate Structure Constant Matrix for a given set of bases"""
    
    n = X[0].shape[0] # Size of Matrix
    m = len(X) # Size of the Basis Set
    sc_mat = np.zeros((m, m, m)) # Empty Structure Constant Matrix

    for j in range(m): # Loop over j (first index)
        for i in range(m): # Loop over i (second index)
            for k in range(m): # Loop over k (third index)
                if np.allclose(Lie_bracket(X[j], X[k])@np.linalg.inv(X[i]), np.eye(n)):
                    sc_mat[j][i][k] = 1
                elif np.allclose(Lie_bracket(X[j], X[k])@np.linalg.inv(X[i]), -np.eye(n)):
                    sc_mat[j][i][k] = -1
                else:
                    sc_mat[j][i][k] = 0
                    
    return sc_mat

In [320]:
X = generate_pauli_bases(1)

S = structure_constant(X)

##### Root Finding

To find the root of the linear map $\text{ad_X}:

1. Find the matrix representation of $\text{ad_X}$ with respect to the basis

2. Find the eigenvalues of the basis

3. Find the eigenvectors of the basis

In [327]:
H = 1/(np.sqrt(2)*2)*np.array([[1, 1], [1, -1]])

In [328]:
Lie_bracket(1j/2*X1, H)

array([[0.+0.j        , 0.-0.35355339j],
       [0.+0.35355339j, 0.+0.j        ]])

In [329]:
Lie_bracket(1j/2*X2, H)

array([[-0.35355339+0.j,  0.35355339+0.j],
       [ 0.35355339+0.j,  0.35355339+0.j]])

In [330]:
Lie_bracket(1j/2*X3, H)

array([[0.+0.j        , 0.+0.35355339j],
       [0.-0.35355339j, 0.+0.j        ]])

In [311]:
M = np.array([[0, 0, 0], 
              [1, 0, -1j], 
              [0, -1, 0]])

In [312]:
D, P = np.linalg.eig(M)

In [313]:
D

array([ 0.70710678+0.70710678j, -0.70710678-0.70710678j,
        0.        +0.j        ])

In [314]:
Matrix(np.round(P, 14))

Matrix([
[               0,                0,    0.70710678118655],
[0.70710678118655,      0.5 + 0.5*I,                   0],
[    -0.5 + 0.5*I, 0.70710678118655, -0.70710678118655*I]])

In [317]:
W = 1/np.sqrt(2)*X3 + (0.5+0.5j)*X2

In [318]:
Lie_bracket(H, W)

array([[ 0.5       -0.5j, -1.20710678+0.5j],
       [ 0.20710678+0.5j, -0.5       +0.5j]])

In [319]:
W * D[0]

array([[ 0.5       +0.5j, -0.70710678+0.j ],
       [ 0.70710678+0.j , -0.5       -0.5j]])